api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "optimaio-cart-transform"
type = "function"
uid = "94a3e254-ad2e-e397-bf13-eae56eded77899533499"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
